# Generated by Django 6.0 on 2026-01-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testcase_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.SlugField(max_length=20, unique=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('test_cases', models.FileField(upload_to='testcase/')),
            ],
        ),
    ]
