# Generated by Django 6.0 on 2026-02-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_submission_table",
            fields=[
                ("submission_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.SlugField(max_length=20)),
                ("problem_id", models.SlugField(max_length=20)),
                ("code_file", models.FileField(upload_to="user_code/")),
                ("language_used", models.CharField(max_length=30)),
                ("submission_time", models.DateTimeField(auto_now_add=True)),
                ("toal_problems_solved", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name="testcase_table",
            new_name="problem_table",
        ),
    ]
